name = "hugle"
license = "MIT"
licenselink = "https://github.com/ahampriyanshu/hugle/blob/main/LICENSE"
description = "Google Docs styled blog theme in Hugo."
homepage = "https://ahampriyanshu.com/blog"
tags = [
  "blog",
  "portfolio"
]

features = [
  "blog",
  "portfolio"
]

baseURL = 'https://ahampriyanshu.com/blog'
languageCode = 'en-us'
title = 'ahampriyanshu'
theme="hugle"

[sitemap]
  changeFreq = 'weekly'
  filename = 'sitemap.xml'
  priority = 0.8